// flow-typed signature: ae9211edb01afb27ccef517085e93316
// flow-typed version: <<STUB>>/express-promise-router_v^3.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-promise-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-promise-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-promise-router/lib/express-promise-router' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/express-promise-router.route.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/express-promise-router.test' {
  declare module.exports: any;
}

declare module 'express-promise-router/test/typescript.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-promise-router/lib/express-promise-router.js' {
  declare module.exports: $Exports<'express-promise-router/lib/express-promise-router'>;
}
declare module 'express-promise-router/test/express-promise-router.route.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/express-promise-router.route.test'>;
}
declare module 'express-promise-router/test/express-promise-router.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/express-promise-router.test'>;
}
declare module 'express-promise-router/test/typescript.test.js' {
  declare module.exports: $Exports<'express-promise-router/test/typescript.test'>;
}
