// flow-typed signature: ce7a8c4e233b0b7f8a92c84ab1748a59
// flow-typed version: <<STUB>>/pg-assert-schema_v^2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-assert-schema'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-assert-schema' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-assert-schema/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-assert-schema/cli.js' {
  declare module.exports: $Exports<'pg-assert-schema/cli'>;
}
declare module 'pg-assert-schema/index' {
  declare module.exports: $Exports<'pg-assert-schema'>;
}
declare module 'pg-assert-schema/index.js' {
  declare module.exports: $Exports<'pg-assert-schema'>;
}
