// flow-typed signature: 89a99f46d92508f698fb885aade694a9
// flow-typed version: <<STUB>>/pg-require-sql_v1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pg-require-sql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pg-require-sql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pg-require-sql/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pg-require-sql/index' {
  declare module.exports: $Exports<'pg-require-sql'>;
}
declare module 'pg-require-sql/index.js' {
  declare module.exports: $Exports<'pg-require-sql'>;
}
declare module 'pg-require-sql/test/index.js' {
  declare module.exports: $Exports<'pg-require-sql/test/index'>;
}
